import type { LostPet } from "@/types";

export const mockLostPets: LostPet[] = [
  {
    id: "LP-00001",
    petName: "Milo",
    species: "CAT",
    color: "Orange tabby",
    pattern: "Tabby stripes, white chest",
    description: "Milo escaped through an open window on June 24. He is neutered, microchipped, and very friendly. He loves people and will approach if you call his name.",
    hasCollar: true,
    collarDescription: "Teal collar with a small bell and tag",
    status: "ACTIVE",
    photoUrls: ["https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80"],
    location: { latitude: 13.7780, longitude: 100.5480, district: "Ari", isExact: false },
    lastSeenAt: "2026-06-24T06:00:00Z",
    createdAt: "2026-06-24T09:00:00Z",
    matchCount: 2,
    owner: { id: "u4", displayName: "Priya S.", phone: "081-234-5678" },
  },
  {
    id: "LP-00002",
    petName: "Luna",
    species: "DOG",
    color: "Golden",
    pattern: "Solid",
    description: "Luna is a 2-year-old golden retriever. She got out during a thunderstorm on June 25. She is gentle, vaccinated, and responds to her name. She has a microchip.",
    hasCollar: true,
    collarDescription: "Pink collar with a heart-shaped tag engraved 'Luna'",
    status: "ACTIVE",
    photoUrls: ["https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80"],
    location: { latitude: 13.8010, longitude: 100.5510, district: "Chatuchak", isExact: false },
    lastSeenAt: "2026-06-25T19:00:00Z",
    createdAt: "2026-06-25T20:30:00Z",
    matchCount: 1,
    owner: { id: "u5", displayName: "Tom W.", phone: "089-876-5432" },
  },
  {
    id: "LP-00003",
    petName: "Simba",
    species: "CAT",
    color: "Black and white",
    pattern: "Tuxedo",
    description: "Simba is a tuxedo cat who went missing near Victory Monument. He was found and reunited with his owner after a community effort.",
    hasCollar: false,
    status: "FOUND",
    photoUrls: [],
    location: { latitude: 13.7655, longitude: 100.5370, district: "Victory Monument", isExact: false },
    lastSeenAt: "2026-06-20T00:00:00Z",
    createdAt: "2026-06-20T10:00:00Z",
    matchCount: 0,
    owner: { id: "u6", displayName: "Dao M." },
  },
];
