import type { Sighting } from "@/types";

export const mockSightings: Sighting[] = [
  {
    id: "SGT-00001",
    species: "CAT",
    color: "Orange tabby",
    pattern: "Tabby stripes",
    description: "Friendly orange tabby seen near Ari BTS exit 1. Appears thin but healthy. Has a slight limp on front right leg. Responds to food.",
    status: "POSSIBLE_LOST",
    urgency: "MEDIUM",
    verificationStatus: "VERIFIED",
    photoUrls: ["https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80"],
    location: { latitude: 13.7762, longitude: 100.5498, district: "Ari", isExact: false },
    seenAt: "2026-06-26T08:30:00Z",
    createdAt: "2026-06-26T08:35:00Z",
    reporter: { id: "u2", displayName: "Somchai R.", role: "REPORTER" },
  },
  {
    id: "SGT-00002",
    species: "DOG",
    color: "Golden",
    pattern: "Solid",
    description: "Medium-sized golden dog near Chatuchak Weekend Market. Wearing a faded red collar without tag. Seems friendly and well-fed, possibly escaped from nearby home.",
    status: "POSSIBLE_LOST",
    urgency: "HIGH",
    verificationStatus: "VERIFIED",
    photoUrls: ["https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80"],
    location: { latitude: 13.7999, longitude: 100.5505, district: "Chatuchak", isExact: false },
    seenAt: "2026-06-26T10:15:00Z",
    createdAt: "2026-06-26T10:20:00Z",
    reporter: { id: "u3", displayName: "Karn T.", role: "REPORTER" },
  },
  {
    id: "SGT-00003",
    species: "CAT",
    color: "Black and white",
    pattern: "Tuxedo",
    description: "Tuxedo cat with injured back leg near Victory Monument. Unable to walk properly. Urgent rescue needed. Hiding under food stall.",
    status: "RESCUE_NEEDED",
    urgency: "EMERGENCY",
    verificationStatus: "VERIFIED",
    photoUrls: ["https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=600&q=80"],
    location: { latitude: 13.7652, longitude: 100.5373, district: "Victory Monument", isExact: false },
    seenAt: "2026-06-26T07:00:00Z",
    createdAt: "2026-06-26T07:10:00Z",
    reporter: { id: "u1", displayName: "Nicha P.", role: "VOLUNTEER" },
  },
  {
    id: "SGT-00004",
    species: "DOG",
    color: "Brown and white",
    pattern: "Spotted",
    description: "Small beagle mix wandering near Lat Phrao intersection. Appears scared, stays close to walls. No collar. Possibly abandoned.",
    status: "STRAY",
    urgency: "MEDIUM",
    verificationStatus: "PENDING",
    photoUrls: [],
    location: { latitude: 13.8101, longitude: 100.5694, district: "Lat Phrao", isExact: false },
    seenAt: "2026-06-25T16:45:00Z",
    createdAt: "2026-06-25T16:50:00Z",
    reporter: { id: "u2", displayName: "Somchai R.", role: "REPORTER" },
  },
  {
    id: "SGT-00005",
    species: "CAT",
    color: "Gray",
    pattern: "Solid",
    description: "Gray short-hair cat in Ratchada area. Looks healthy and well-groomed, likely lost pet. Very friendly and follows people.",
    status: "POSSIBLE_LOST",
    urgency: "LOW",
    verificationStatus: "VERIFIED",
    photoUrls: ["https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=600&q=80"],
    location: { latitude: 13.7770, longitude: 100.5675, district: "Ratchada", isExact: false },
    seenAt: "2026-06-25T14:20:00Z",
    createdAt: "2026-06-25T14:25:00Z",
    reporter: { id: "u3", displayName: "Karn T.", role: "REPORTER" },
  },
  {
    id: "SGT-00006",
    species: "CAT",
    color: "White",
    pattern: "Solid",
    description: "White cat with blue eyes near Saphan Khwai. Appears to be a Persian mix. Well-groomed but lost.",
    status: "POSSIBLE_LOST",
    urgency: "MEDIUM",
    verificationStatus: "VERIFIED",
    photoUrls: [],
    location: { latitude: 13.7879, longitude: 100.5449, district: "Saphan Khwai", isExact: false },
    seenAt: "2026-06-25T11:00:00Z",
    createdAt: "2026-06-25T11:05:00Z",
    reporter: { id: "u1", displayName: "Nicha P.", role: "VOLUNTEER" },
  },
  {
    id: "SGT-00007",
    species: "DOG",
    color: "Black",
    pattern: "Solid",
    description: "Large black dog near Bang Sue Grand Station. Appears thin and malnourished. Limping. Urgent care needed.",
    status: "INJURED",
    urgency: "HIGH",
    verificationStatus: "VERIFIED",
    photoUrls: [],
    location: { latitude: 13.8055, longitude: 100.5356, district: "Bang Sue", isExact: false },
    seenAt: "2026-06-24T09:30:00Z",
    createdAt: "2026-06-24T09:35:00Z",
    reporter: { id: "u2", displayName: "Somchai R.", role: "REPORTER" },
  },
  {
    id: "SGT-00008",
    species: "OTHER",
    color: "Brown",
    pattern: "Solid",
    description: "Small rabbit found wandering near Din Daeng. Appears domestic. No markings. Needs temporary shelter.",
    status: "STRAY",
    urgency: "LOW",
    verificationStatus: "PENDING",
    photoUrls: [],
    location: { latitude: 13.7705, longitude: 100.5472, district: "Din Daeng", isExact: false },
    seenAt: "2026-06-24T13:00:00Z",
    createdAt: "2026-06-24T13:10:00Z",
    reporter: { id: "u3", displayName: "Karn T.", role: "REPORTER" },
  },
];
